[project]
name = "{{ cookiecutter.directory_name }}"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "acdh-tei-pyutils>=1.6",
    "jinja2>=3.1.6",
    "typesense>=1.1.1",
]
