name: Build and publish

on: 
  push:

jobs:
  build_pages:
    name: Publish Edition as GitHub Pages Website
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Install Saxon, Ant and Python
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./shellscripts/script.sh
        pip install -r requirements.txt
    - name: Build
      run: |
        ant{% if cookiecutter.translations == 'yes' %}
    - name: Update Translations
      run: python make_translations.py{% endif %}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ "{{" }}secrets.GITHUB_TOKEN{{ "}}" }}
        publish_dir: ./html
